source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'NotificationManager_Tests' do
  pod "NotificationManager", :path => "../"

  pod 'Quick', '~> 1.1.0'
  pod 'Nimble', '~> 7.0'
end
